title: vizi
description: A viewer for volumetric scientific image data.
url: https://vizi.science
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  style: compressed
