title: vizi
description: A viewer for volumetric scientific image data.
url: https://focolab.github.io
baseurl: /vizi-website

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  style: compressed
